#!/usr/bin/env bash
# Render the runtime env file for an environment by merging, in order of
# increasing precedence:
#
#   1. env/common.env.example   (shared non-secret defaults)
#   2. env/<env>.env.example    (env-specific non-secret config)
#   3. versions/<env>.env       (pinned image tags)
#   4. SECRETS from the process environment (exported by the GitHub Actions
#      deploy job from GitHub Environment secrets)
#
# Output: env/<env>.runtime.env (chmod 600, git-ignored). docker compose then
# consumes it via --env-file. Later layers win because --env-file keeps the
# last definition of a duplicated key.
#
# Usage:  POSTGRES_PASSWORD=... GHCR_TOKEN=... scripts/render-env.sh staging
#         SKIP_SECRETS=1 scripts/render-env.sh staging   # offline (no secrets)
set -euo pipefail

ENV_NAME="${1:?usage: render-env.sh <staging|production>}"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

common="$REPO_DIR/env/common.env.example"
envfile="$REPO_DIR/env/${ENV_NAME}.env.example"
versions="$REPO_DIR/versions/${ENV_NAME}.env"
out="$REPO_DIR/env/${ENV_NAME}.runtime.env"

for f in "$common" "$envfile" "$versions"; do
  [[ -f "$f" ]] || { echo "ERROR: missing $f" >&2; exit 1; }
done

# Secrets expected in the environment. GHCR_USER is non-secret but travels with
# the GHCR token. TRAEFIK_DASHBOARD_AUTH is staging-only (optional).
REQUIRED_SECRETS=(
  POSTGRES_PASSWORD
  GHCR_USER
  GHCR_TOKEN
  JWT_SIGNING_KEY
)
OPTIONAL_SECRETS=(
  TRAEFIK_DASHBOARD_AUTH
  # Kredar backend — transactional email (Resend).
  RESEND_API_KEY
  # Kredar backend — Nomba integration.
  NOMBA_CLIENT_ID
  NOMBA_CLIENT_SECRET
  NOMBA_ACCOUNT_ID
)

# Keep only KEY=VALUE lines (drop comments/blanks) from the non-secret layers.
keep_kv() { grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "$1" || true; }

umask 077
{
  echo "# AUTO-GENERATED by render-env.sh for ${ENV_NAME} — do not edit or commit."
  keep_kv "$common"
  keep_kv "$envfile"
  keep_kv "$versions"

  if [[ "${SKIP_SECRETS:-0}" != "1" ]]; then
    for v in "${REQUIRED_SECRETS[@]}"; do
      if [[ -z "${!v:-}" ]]; then
        echo "ERROR: required secret '$v' is not set in the environment" >&2
        exit 1
      fi
      printf '%s=%s\n' "$v" "${!v}"
    done
    for v in "${OPTIONAL_SECRETS[@]}"; do
      [[ -n "${!v:-}" ]] && printf '%s=%s\n' "$v" "${!v}" || true
    done
  else
    echo "# SKIP_SECRETS=1: secrets omitted (offline render)" >&2
  fi
} > "$out"

chmod 600 "$out"
echo "Rendered $out"
